redhat/diydrones-repo.spec, redhat/diydrones.repo, scripts/build_rpm.sh, scripts/deploy_rpm.sh, scripts/prepare_rpm.pl
I've added configs to support Yum repository for RedHat-based distros.
So, if anyone is pllanning on deploying APM Planner 2 this configs would help.
yum install http://www.froller.net/diydrones/noarch/diydrones-repo-1-1.noarch.rpm
yum install apmplanner2
when the update would be available:
yum update apmplanner2
=> Yum repository support

src/ui/AP2DataPlot2DModel.cc
Several fixes:
- FMTs don't appear to take an index slot
- number of columns must be adjusted for idx and message type
- a few missing format types added (not done exhaustively)
=> AP2DataPlot2DModel: corrections to facilitate export of data to .log

libs/opmapcontrol/src/mapwidget/waypointitem.h, src/ui/WaypointEditableView.cc, src/ui/WaypointEditableView.h, src/ui/map/QGCMapWidget.cc, src/ui/map/QGCMapWidget.h
Some map/ mission widget improvements and fix for issue #691
=> Map improvements

src/ui/AP2DataPlot2D.cpp, src/ui/qcustomplot.cpp, src/ui/qcustomplot.h
This is the update to last version - Fix for #904 
It was much easier than I thought. I just had to make 2 changes.
=> Updated graphic framework to QCustomPlot V1.3.2 - Fixes #904

src/ui/AP2DataPlot2D.cpp, src/ui/AP2DataPlot2D.h, src/ui/AP2DataPlot2DModel.cc, src/ui/AP2DataPlot2DModel.h, src/ui/AP2DataPlotThread.cc, src/ui/AP2DataPlotThread.h
Hi all, I have made some enhancements for the graph view.
Take a look and check if you like them. 
@billbonney  I made only one PR for several changes this time. Just let me know if you prefer one PR for one feature / bugfix - I will rearrange the commits then.
=> Graph View: Several enhancements and a bugfix

src/ui/AP2DataPlot2D.cpp, src/ui/AP2DataPlot2D.h
Fixes: a static data member with an in-class initializer must have non-volatile const integral type - type is 'const double'
I added a prefix too - thought a constant should have one.
=> Build fix for C++03

src/ui/AP2DataPlot2D.cpp, src/ui/AP2DataPlotThread.cc
Made a fix for #859 - was a 'low hanging fruit' :-) and some refactoring.
=> Graph View: BugFix for "Graph Scale Control" issue. Fixes #859

src/ui/AP2DataPlotThread.cc
Was too slow my last PR was already merged :-)
This is a bugfix for handling tlogs with time stamps which are decreasing during log reading.
The time stamp of those messages is then overwritten with the last valid value to keep the integrity of the datamodel. Also a parsing error is shown to the user.
Added some comments to keep code structured...
=> Graph View: Check for increasing time when reading tlogs.

src/ui/uas/UASActionsWidget.cpp
Useful for testing camera/trigger components
=> Info View: added camera trigger

src/ui/AP2DataPlot2D.cpp, src/ui/AP2DataPlotThread.cc, src/ui/AP2DataPlotThread.h
Developed a crash-fix with AndKe for a SIGSEGV which was only reproducible on his systems. Take a look at #940 for further information.
Moreover I found a memleak perhaps introduced by myself :unamused:
=> Removed memleak and a crash fix Fixes #940

deploy/MUI2.nsh, deploy/apm_installer_win.nsi, deploy/x64.nsh
Added Microsoft Visual C++ 2015 Redistributable (x64) and Microsoft
Visual C++ 2015 Redistributable (x86). Also, made changes to the NSIS
script for native Windows build.
=> NSIS Script : Updates for Windows

src/uas/ApmUiHelpers.cc, src/uas/ArduPilotMegaMAV.cc, src/uas/ArduPilotMegaMAV.h
Added new messages to the message formatter class and extended the MODE message class to handle the new reason field.
=> Adapted MSG formatter for use with AC 3.4 Fixes #955

src/main.cc, src/ui/DebugOutput.cc, src/ui/DebugOutput.h, src/ui/MainWindow.cc, src/ui/MainWindow.h
Debug log window is now working again.
Adapted DebugOutput class and created LogWindowSingleton class which is just a helper for buffering and some sort of adapter for the loggingMessageHandler which can only operate on static data.
=> Logging: Adapted debug log window to new logging system

src/ui/AP2DataPlot2D.cpp
ArduPilot projects log to .BIN (uppercase)
=> Graph: display .BIN files too (uppercase) when selecting log.

src/ui/configuration/RadioCalibrationConfig.cc
ELEVON_OUTPUT values are now between 1 and 8.
=> RadioCalibration: add new ELEVON_OUTPUT values

src/Waypoint.cc, src/comm/QGCFlightGearLink.cc, src/comm/QGCJSBSimLink.cc, src/uas/UAS.cc, src/uas/UASManager.cc, src/ui/HUD.cc, src/ui/LogParser/AsciiLogParser.cpp, src/ui/LogParser/BinLogParser.cpp, src/ui/PrimaryFlightDisplay.cc
I replaced all isinf() and isnan() by qIsInf() and qIsNaN() and made a clean build on ubuntu 16.04 with Qt 5.4.2, 5.5.1 and 5.6.2. All builds were OK and a quick startup works as normal.
This should fix the build issues with Qt 5.6.X referenced in #959
=> Replaced all isinf() and isnan()

src/uas/ArduPilotMegaMAV.cc, src/uas/ArduPilotMegaMAV.h, src/ui/AP2DataPlot2D.cpp, src/ui/LogdataStorage.cpp, src/ui/LogdataStorage.h
Hi,
I added an optimized method to the log-storage for getting values. It avoids an additional copy of the data. Moreover all log data that haves strings as values are suppressed in the Graph tree, as it is not useful to plot them. If we get more text messages they should be handled like error, mode,... messages.
Next I updated the copter log formatters to reflect the latest changes in ArduPilot.
=> Graph view improvements

.travis.yml, README.md, debian/control, sik_uploader/sik_uploader.py
the fix is provided by RHHoek - all credit to him.
=> SiK_uploader fixed

libs/opmapcontrol/src/internals/core.cpp, libs/opmapcontrol/src/mapwidget/waypointitem.cpp, libs/opmapcontrol/src/mapwidget/waypointitem.h, src/Waypoint.cc, src/uas/UASWaypointManager.cc, src/uas/UASWaypointManager.h, src/ui/LogAnalysis.ui, src/ui/Loghandling/BinLogParser.cpp, src/ui/Loghandling/LogAnalysis.cpp, src/ui/Loghandling/LogAnalysis.h, src/ui/WaypointList.ui, src/ui/WaypointNavigation.cc, src/ui/WaypointNavigation.h, src/ui/WaypointViewOnlyView.cc, src/ui/map/QGCMapTool.cc, src/ui/map/QGCMapWidget.cc, src/ui/map/Waypoint2DIcon.cc, src/ui/map/Waypoint2DIcon.h, src/ui/uas/UASQuickViewItemSelect.cc, src/ui/uas/UASQuickViewItemSelect.h
After fixing the bug made in last PR here is the replacement for #1025 
Here is the list of what have been fixed:
* #1019 - FlightPlan:multiple waypoints are moving together after load.
* #1022 - Graph: .BIN Logs made with GPXS , GRXH, EKF5 causing slow performance and lots of errors. 
* #1023 - Graph: where did "filter" go ? 
* #1024 - Plan/Flight data , orphaned lines between waypoints.
I hope this time nobody finds a bug :smiley:
=> Several Bug fixes

src/ui/MainWindow.cc
It follows some user that were lost with this error on ardupilot discuss
=> MainWindow: update helper to add user to dialout

src/output/kmlcreator.cc, src/output/kmlcreator.h, src/ui/Loghandling/LogAnalysis.cpp, src/ui/Loghandling/LogAnalysis.h, src/ui/Loghandling/LogExporter.cpp, src/ui/Loghandling/LogExporter.h
supersedes #1039
rebased on master
cleaned up the GPS to UTC time conversion, now matches time_epoch_convert() in  AP_GPS.h
Also breaks up flight path into timestamped 1 second segments
=> WIP: enhancement, add timestamps to flightpath and plane placemarks

README.md, src/globalobject.cc, src/ui/MainWindow.cc
See comments on the commits for further information
=> Small fixes

qml/components/AltitudeIndicator.qml, qml/components/StatusMessageIndicator.qml
* add the min and max altitude to AltitudeIndicator to extend the graticule . fixes #1034
* add word wrap to the text of StatusMessageIndicator.  fixes #930
=> FlightDisplay: extend the range of altitude Indicator and add wordwrap to message

README.md, libs/opmapcontrol/src/core/cache.cpp, src/ui/AP2DataPlot2D.cpp, src/ui/Loghandling/PresetManager.cpp
Made some small fixes. Description is in commit msg.
=> Several small fixes

src/ui/WaypointViewOnlyView.cc
=> fix MAV_CMD_DO_TRIGGER_CONTROL label in Onboard Waypoints list

libs/opmapcontrol/src/core/maptype.h, libs/opmapcontrol/src/core/opmaps.cpp, libs/opmapcontrol/src/core/urlfactory.cpp, src/ui/map/QGCMapToolBar.cc
=> Map: added Eniro as map for Norway,Sweden,Finland,Denmark,Poland

src/ui/uas/UASActionsWidget.cpp
Older set speed were updating an parameter. (deprecated method)
This change uses MAV_CMD_DO_CHANGE_SPEED
=> Info View: fix set speed

apm_planner.pro
was already tested and reviewed
=> Build: Enabled c++ 11 support for all plattforms

.travis.yml, apm_planner.pro, src/configuration.h
- Updated for 2.0.26-rc1 for beta testing
- Updates Travis to use Qt 5.9.3 
- macOS 10.12 Xcode 9.2
- linux
=> build: Update to 2.0.26-rc1

src/ui/AboutDialog.ui
Fixed link to credits, it is now
http://ardupilot.org/planner2/docs/credits-and-contributors.html.
=> About Dialog: Fixed credits link

src/logging.h, src/main.cc, src/ui/Loghandling/LogAnalysis.cpp, src/ui/Loghandling/LogAnalysis.h, src/ui/Loghandling/LogExporter.cpp, src/ui/Loghandling/LogExporter.h
Several bug fixes - perhaps someone wants to review :smile:
=> Some fixes

libs/opmapcontrol/src/core/maptype.h, libs/opmapcontrol/src/core/opmaps.cpp, libs/opmapcontrol/src/core/urlfactory.cpp, src/ui/map/QGCMapToolBar.cc
=> Maps: statkart (map-source) updated to v4

src/ui/map/QGCMapWidget.cc
Bugfix PR.
@AndKe should fix the issue. BUT I do not know why this waypoint type was not handled - only forgotten or on purpose?! Don't if it only fixed the symptom or really the big - test carefully when using real UAV.
=> Mission Widget: Terrain Alt will not loose markers anymore. Fixes #1117

QGCExternalLibs.pri, src/comm/AbsPositionOverview.h, src/comm/LinkManager.h, src/comm/MAVLinkDecoder.h, src/comm/MAVLinkProtocol.cc, src/comm/MAVLinkProtocol.h, src/comm/MissionOverview.h, src/comm/QGCMAVLink.h, src/comm/RelPositionOverview.h, src/comm/UASObject.h, src/comm/VehicleOverview.h, src/main.cc, src/output/kmlcreator.h, src/uas/ArduPilotMegaMAV.cc, src/uas/UAS.cc, src/uas/UAS.h, src/uas/UASWaypointManager.cc, src/ui/EKFMonitor.cpp, src/ui/Loghandling/AP2DataPlotStatus.h, src/ui/Loghandling/LogAnalysis.h, src/ui/Loghandling/LogExporter.h, src/ui/configuration/CompassMotorCalibrationDialog.h
WIP for making mavlink 1.0 communication work again
=> Mavlink 2.0 fixes

src/uas/UAS.cc, src/uas/UAS.h, src/ui/configuration/ApmSoftwareConfig.cc, src/ui/configuration/CopterPidConfig.cc, src/ui/configuration/CopterPidConfig.h, src/ui/configuration/CopterPidConfig.ui
This PR adapts the extended tuning setup view for use with arducopter 3.6 and improves the parameter handling.
=> Extended tuning fixes

src/ui/configuration/BasicPidConfig.cc, src/ui/configuration/BasicPidConfig.h, src/ui/configuration/CopterPidConfig.cc
Basic tuning should now work again too.
=> Tuning Setup: Basic tuning adapted parameter names for arducopter 3.6

src/comm/LinkManager.cc, src/comm/LinkManager.h, src/ui/configuration/BasicPidConfig.cc
Store each UDP connection only once even if it is held more than once internally.
=> Link manager fix for #1121

src/ui/QGCMAVLinkInspector.cc, src/ui/QGCMAVLinkInspector.ui
As headline states - simple statistics (received and dropped packets) for the mavlink inspector widget.
=> MavLink Inspector: Added simple mavlink statistics

src/ui/Loghandling/BinLogParser.cpp, src/ui/Loghandling/BinLogParser.h
NaN detection changed from detecting soft NaN and treat every other value as hard NaN to detecting hard NaN and treat all other as soft NaN.
=> GraphView: Changed NaN detection Fixes #1144

src/ui/Loghandling/LogAnalysis.cpp, src/ui/Loghandling/LogAnalysis.h, src/ui/Loghandling/TlogParser.cpp
First commit should fix issue #1155
=> Some Bugfixes

src/uas/UAS.cc, src/ui/configuration/RadioCalibrationConfig.cc, src/ui/configuration/RadioCalibrationConfig.h, src/ui/configuration/RadioCalibrationConfig.ui
Radio config dialog will now work again when using MAVLink 2.
Supports now up to 16 RC channels.
Fixes #1153
=> Radio Setup: Added compatibility for MAVLink 2 and increased to 16 channels

apm_planner.pro, src/ui/configuration/ApmFirmwareConfig.cc, src/ui/configuration/ApmFirmwareConfig.h, src/ui/configuration/PX4FirmwareUploader.cc
should be possible to update a pixhawk v4 now - untested!
=> WIP: Frimware update improve

apm_planner.pro, src/ui/configuration/ApmFirmwareConfig.cc, src/ui/configuration/PX4FirmwareUploader.cc, src/ui/configuration/PX4FirmwareUploader.h
Some more changes for firmware update.
* Stop scannig for new devices if flashing has started
* better logging
* removed OpenSSL requirement from flash module is not needed anymore
=> Fmuv5 fixes

apm_planner.pro, libs/opmapcontrol/src/mapwidget/gpsitem.cpp, libs/opmapcontrol/src/mapwidget/gpsitem.h, libs/opmapcontrol/src/mapwidget/opmapwidget.cpp, libs/opmapcontrol/src/mapwidget/opmapwidget.h, src/ui/LogAnalysisMap.ui, src/ui/Loghandling/LogAnalysis.cpp, src/ui/Loghandling/LogAnalysis.h, src/ui/Loghandling/LogAnalysisMap.cpp, src/ui/Loghandling/LogAnalysisMap.h
Hi all,
after a long time I decided to develop a new cool feature for the log analysis feature of the APM-Planner.
We do now support showing the GPS Trail of a logged flight. The feature looks like this:
There is a new menu entry called View in the log analysis window. It will open the new window showing the trail and an multicopter icon representing the current position. The Icon moves on the trail when you enable and move the table cursor in the graph.
I hope you like it :smile:
=> New Gps trail Feature

files/ardupilotmega/arducopter.pdef.xml, src/uas/ArduPilotMegaMAV.cc, src/uas/ArduPilotMegaMAV.h
1. I created the configuration parameter file for AC 3.6.9 release version with the following command.
./Tools/scripts/build_parameters.sh
2. I added the throwing mode and the zigzag mode to the flight mode selection item.
=> Copter: Change to setting parameter of AC 3.6.9 release version.

libs/opmapcontrol/src/core/maptype.h, libs/opmapcontrol/src/core/opmaps.cpp, libs/opmapcontrol/src/core/urlfactory.cpp, src/ui/map/QGCMapToolBar.cc
I live in Japan.
I have many mountainous areas in Japan.
I want to use a map with elevations.
I want to be able to use the map of the Geographical Survey Institute of Japan.
=> map: Added Japan Map

src/uas/UAS.cc, src/ui/configuration/CameraGimbalConfig.cc, src/ui/configuration/FrameTypeConfig.cc
Frame config will now work with ardupilot 4.0.0
Fixed some wrong parameter names in camera setup
=> Small bugfixes

README.md, apm_planner.pro, apm_planner_version.json, docker/2.0.20-wily64/Dockerfile, docker/2.0.24-xenial64/Dockerfile, src/ui/AboutDialog.ui, src/ui/AutoUpdateCheck.h, src/ui/configuration/ApmFirmwareConfig.cc, src/ui/configuration/ApmSoftwareConfig.cc
=> Adjust for ardupilot's move to https

Vagrantfile
The scripts make iterative development easier for those that don't
compile every day
=> Vagrantfile: move to xenial64; write scripts for compilation

src/ui/configuration/BasicPidConfig.cc, src/ui/configuration/CopterPidConfig.cc, src/ui/configuration/CopterPidConfig.h, src/ui/configuration/CopterPidConfig.ui
* Added new filters to extended tuning
* Added feed forwared paramter to extended tuning
* Updated tune & rc options dropdown lists
* Updated Parameters in basic and extended tuning
=> Tuning Setup: Added support for Arducopter 4.0 Fixes #1193

src/ui/AP2DataPlot2D.cpp, src/ui/AP2DataPlot2D.h, src/ui/Loghandling/PresetManager.cpp, src/ui/Loghandling/PresetManager.h
=> GraphView: File dialog does not use signal/slot mechanism anymore.

Vagrantfile
Focal doesn't run on my machine as a VM.  So move forward to something I've
tested....
=> Vagrantfile: move to Bionic

README.md
=> General: Updated README.md Fixes #1200

qml/PrimaryFlightDisplayQML.qml, qml/components/AltitudeIndicator.qml
=> Allow 2000m in PFD altitude indicator. Fixes #1239

src/ui/AP2DataPlot2D.cpp, src/ui/AP2DataPlot2D.h
Additionally some cleanup and performance tweaks.
=> GraphView: Don't use exponent in Graph view anymore. Fixes #1150

src/ui/Loghandling/LogAnalysis.cpp, src/ui/Loghandling/LogdataStorage.cpp, src/ui/PrimaryFlightDisplayQML.cpp, src/ui/VibrationMonitor.cpp
Scaled models only.
Some other minor fixes.
=> GraphView: Fix table cursor not moving when selecting table row. 

src/ui/Loghandling/TlogParser.cpp
=> Graph View: Ignore GCS messages when parsing Tlogs. Fixes #1251

sik_uploader/sik_uploader.py
=> Imported new Sik uploader from  https://github.com/ArduPilot/SiK

src/uas/ArduPilotMegaMAV.cc, src/uas/ArduPilotMegaMAV.h, src/ui/Loghandling/LogParserBase.cpp, src/ui/configuration/ApmSoftwareConfig.cc
Modes for fixed wing should be showed correctly in Graph view now. Also added support for event messages. Fixes #1285
=> Fix arduplane modes

CONTRIBUTING.md
@Arne-W I create this possible improvement. I'm happy to discuss about it
=> Improve documentation for PR associated to 3rd parties libs or framework

apm_planner_version.json, src/ui/AutoUpdateCheck.cc, src/ui/AutoUpdateCheck.h, src/ui/AutoUpdateDialog.cc
Reeneable the the Update check for APM-Planner.  Did a lot of refactoring. The json file has to be updated when we do the next release.
=> Fix and refactor Auto update check

qml/ApmToolBar.qml, qml/EKFMonitor.qml, qml/PrimaryFlightDisplayQML.qml, qml/VibrationMonitor.qml, qml/components/AltitudeIndicator.qml, qml/components/BarGauge.qml, qml/components/Button.qml, qml/components/CompassIndicator.qml, qml/components/DigitalDisplay.qml, qml/components/HeartbeatDisplay.qml, qml/components/InformationOverlayIndicator.qml, qml/components/ModeDisplay.qml, qml/components/PitchIndicator.qml, qml/components/RollPitchIndicator.qml, qml/components/SpeedIndicator.qml, qml/components/StatusDisplay.qml, qml/components/StatusMessageIndicator.qml, qml/components/TextButton.qml, src/ui/ApmToolBar.cc, src/ui/ApmToolBar.h, src/ui/EKFMonitor.cpp, src/ui/EKFMonitor.h, src/ui/PrimaryFlightDisplayQML.cpp, src/ui/PrimaryFlightDisplayQML.h, src/ui/VibrationMonitor.cpp, src/ui/VibrationMonitor.h
- Fix Graphic issues with QML widgets (missing content)
- Update QtQuick to 2.9 
- Modernize c++ in files that have changed
=> Fix some graphic issues

src/ui/qcustomplot.cpp
There was a fall through warning during build.
I will change this warning.
=> ui: Addressing fall through warnings

src/ui/Loghandling/LogParserBase.cpp, src/ui/Loghandling/LogdataStorage.cpp, src/ui/Loghandling/LogdataStorage.h
Fixed handling of Unit data containing a dot and did some C++ modernizing.
=> Fix unidata with dot

src/ui/Loghandling/LogdataStorage.cpp, src/ui/Loghandling/LogdataStorage.h
Indexed  data types should work now even if they have gaps.
=> Fix indexed types with gaps

src/ui/configuration/AccelCalibrationConfig.cc, src/ui/configuration/AccelCalibrationConfig.h, src/ui/configuration/AccelCalibrationConfig.ui
Fixes issue with acclerometer calibration not working on newer Ardupilot FWs.
=> 1315: Fix accel calibration

apm_planner.pro, libs/mavlink/include/mavlink/v2.0/mavlink_helpers.h, src/uas/UAS.cc, src/uas/UAS.h, src/uas/UASInterface.h, src/ui/QGCSettingsWidget.ui, src/ui/configuration/CompassConfig.cc, src/ui/configuration/CompassConfig.h, src/ui/configuration/CompassConfig.ui, src/ui/configuration/CompassMotorCalibrationDialog.cpp, src/ui/configuration/CompassMotorCalibrationDialog.h, src/ui/configuration/CompassOnboardCalibrationDialog.cpp, src/ui/configuration/CompassOnboardCalibrationDialog.h, src/ui/configuration/CompassOnboardCalibrationDialog.ui
Added UI to allow for onboard compass calibration.
TODO: update plot to show report information during progress.
=> Fixes #797: Update UI layout for onboard compass calibration
