ArduPilot/apm_planner

src/ui/WaypointList.ui
By some mistake, Ctrl-L was assigned to wrong button.
=> Mission Widget: button hotkeys fix

src/ui/MissionElevationDisplay.cpp
This adds distance from previous waypoint. Very useful when user needs
to verify/plan a survey grid for proper overlap.
=> Elevation Widget: added distance from previous WP.

libs/opmapcontrol/src/mapwidget/mapripform.cpp, libs/opmapcontrol/src/mapwidget/mapripform.h, libs/opmapcontrol/src/mapwidget/mapripform.ui, libs/opmapcontrol/src/mapwidget/mapripper.cpp, libs/opmapcontrol/src/mapwidget/mapripper.h
Add option when caching maps to auto continue to a desired zoom level. Form allows for both single level and multi-level caching and prompts user at the end of either caching session to stop or continue. Desired zoom level can be changed at any time (unless user prompt is displayed) and will stop at or continue to new desired level.
=> Map Widget: Fixes #701 Add auto map caching option

src/ui/configuration/ApmFirmwareConfig.cc
..so it does not rely on some per-system-random PID that only Qt sees.
=> Firmware Update: Fix Product recognition for Ubuntu

src/ui/AP2DataPlot2D.cpp, src/ui/AP2DataPlotThread.cc
* Increased severity of popup window.
* Added handling for "not a number" while parsing binary logs.
* Make use of m_errorCount to feed back number of errors detected.
=> Graph View: Better handling of corrupted logfiles Fixes #868

src/ui/AP2DataPlot2D.cpp, src/ui/AP2DataPlot2D.h, src/ui/AP2DataPlotThread.cc, src/ui/AP2DataPlotThread.h
As discussed in #868 here is my solution for providing more details about errors raised during log parsing. Hope you like it. If you have any Ideas for better messages or anything else - just let me know.
By the way - I was not able to resize the message box setFixedSize() did not work as expected. It would be good to increase the width.
This is what it looks like now:
By the way during developing I foud out that most of my APM 3.2.1 binary logs have an error during format parsing.
=> Graph View: Create more detailed error message on log loading

src/ui/AP2DataPlot2D.cpp, src/ui/AP2DataPlotThread.cc, src/ui/AP2DataPlotThread.h
While doing some test I noticed that Tlog parsing is very slow and fails sometimes which leads to a segfault due to null-pointer access. So I fixed this and restructured the tlog parsing. This is the result.
* Heavy restructuring of TLOG parsing:
- removed several memleaks and switched to shared pointer
- removed time handling cause using it as index lead to DB errors
- improoved errorhandling uses m_plotState now
- introduced filtering of "EMPTY" messages as they have no format info
* Moved metatype registration to AP2DataPlotThread class
* Fixed null pointer access in AP2DataPlot2D::threadError
=> Graph View: Crash fixing and restructuring of TLOG parsing

src/ui/AP2DataPlot2D.cpp, src/ui/AP2DataPlot2D.h, src/ui/AP2DataPlot2D.ui, src/ui/AP2DataPlot2DModel.cc, src/ui/AP2DataPlot2DModel.h, src/ui/AP2DataPlotThread.cc, src/ui/AP2DataPlotThread.h, src/ui/dataselectionscreen.cpp, src/ui/dataselectionscreen.h
All data in Graph View is plotted against an artificial data index. This is a robust solution as not all logs support a valid time-line but it makes data matching against flight time impossible.
Since arducopter 3.3 all bin logs have a microsec time stamp on every value. So I thought it should be possible to plot the data vs. time and not only vs. index if the log has a valid time-line.
After a lot of work (you know the first feature prototype takes only 20% of the time the whole feature takes) I have made it. if there is a valid time-line you can switch between time or index on x axis, if not the check-box for switching is hidden.
I made 2 screenshots where you can see nearly the same data. First one shows data vs. time and the second shows data vs. index. The plot vs. time looks far …
=> Graph View: Support for plotting data vs. time if all data has microsec timestamp

src/ui/AP2DataPlot2D.cpp
Made a small fix that hides all check boxes in replay tlog (or live) view that have no effect.
=> Graph View: Hide checkboxes in tlog view which have no effect.

src/ui/WaypointList.cc
Okay the second approach for fixing #661 
The real problem was that Qmap find() delivers an iterator to end() if not found. This iterator was directly used to grab the value and the value of an iterator to end() is garbage.
=> Graph View: BugFix for crash while replaying tlog - Fixes #661

src/comm/serialconnection.cc
The crash was caused by an endless loop. 
disconnect USB -> error signal -> call to portError() -> call to disconnect() -> error signal -> call to porError() -> call to disconnect() -> error signal .......
Gave an incredible backtrace - the gdb crashed while generating :smile:
=> Serial Link: Bugfix #946

src/ui/AP2DataPlot2DModel.cc, src/ui/AP2DataPlot2DModel.h, src/ui/AP2DataPlotThread.cc
Hi all,
after reverting my last hack cause it broke the tlog parsing here comes the next approach!
The main issue was that the DB-index for FMT messages was generated by the datamodel and the DB-index for the data rows was generated by the parser.
I migrated the index generation completely into the data model. The only drawback of this solution is a hard coded offset for the data rows. This means the data model can take max 500 FMT lines. If there are more it will generate an Index failure. I don't think this is a real issue as the binary logs only have a quint8 for the message ID which results in max 255 different FMT messages. So the offset of 500 should be big enough.
The other solution - working without offset and let everything be dynamic - leads to the problem that if you receive …
=> Index fix for data model

debian/rules
debian/rules changed due to rename of project file to apm_planner.pro for debian builds.
=> Change to rules for Debian/Ubuntu

src/ui/JoystickWidget.h
Enlarge m_buttonStates array member to next "maximum" value to prevent segfault in case of connecting joystick with more, than 11 buttons (reproducible e.g. with Sony DualShock 3).
Generally, if it's possible, maybe some dynamic container would be even safer here.
=> Enlarge m_buttonStates array to prevent crash

src/ui/LogParser/AsciiLogParser.cpp, src/ui/LogParser/BinLogParser.cpp, src/ui/LogParser/LogParserBase.cpp, src/ui/LogParser/LogParserBase.h, src/ui/LogParser/TlogParser.cpp, src/ui/LogParser/TlogParser.h
Hi all,
my new PR with a fix for #997 and some other goodies :smiley: 
Messages with a datafield mismatch will be "repaired". This means if the number of datafields in a message does not match the number stored in its descriptor the message gets reconstructed. This is done by creating a new message based on the format stored in the descriptor which will be enriched with all valid data which can be found in the original message. Values that are missing will be set to zero and values which can not be collated are dropped. All repairings are logged with its index.
=> Bugfix and some more - Fixes #997

apm_planner.pro, src/main.cc, src/ui/AP2DataPlot2D.cpp, src/ui/AP2DataPlot2D.h, src/ui/AP2DataPlotAxisDialog.cc, src/ui/AP2DataPlotAxisDialog.h, src/ui/AP2DataPlotThread.h, src/ui/LogAnalysis.ui, src/ui/Loghandling/LogAnalysis.cpp, src/ui/Loghandling/LogAnalysis.h, src/ui/Loghandling/LogExporter.cpp, src/ui/Loghandling/LogdataStorage.cpp, src/ui/MissionElevationDisplay.cpp, src/ui/qcustomplot.cpp, src/ui/qcustomplot.h
Hi all,
here is the PR for the Range Cursor feature requested in #1005.
Moreover this PR includes:
* All cursor moving can be done by drag and drop. Selecting a cursor is done by a click
* Cursors can be enabled by checkbox or context menu (right click into graph area).
* Value axis can be scaled with mouse wheel, must be clicked first to select and mouse must be over axis while using mouse wheel.
* The range cursors deliver min, max, delta and average for all enabled graphs.
* Splitted "AP2DataPlot2D" into two classes: AP2DataPlot2D - for the live log view and LogAnalysis for all offline analyzing. 
* Migrated to QCustomPlot 2.0.0-beta (will update to final as soon as it is released)
* Renamed some features, as their names where misleading.
Here is a screenshot:
=> GraphView: Added range cursor feature and did some refactoring

libs/thirdParty/quazip/ioapi.h
Compilation fails on my gentoo box, as quazip doesn't find a definition
of the OF macro.
However, the macro can be substituted by _Z_OF() (stolen from mainline
quazip code). This makes apm_planner compile on Gentoo and doesn't hurt
other systems.
Signed-off-by: Ralf Ramsauer <ralf.ramsauer@oth-regensburg.de>
=> libs: quazip: add definition for OF macro

docker/2.0.20-wily64/Dockerfile, docker/2.0.24-xenial64/Dockerfile
The previous Dockerfile was outdated: the URL to download the firmware was not valid anymore.
This pull request will fix that. In addition, I think that, instead of constantly updating the Dockerfile each time a new release is made, we could refactor the directory 'docker' to contain all the Dockerfiles that have been created for previous and current releases. To this end, we create a sub-directory named "release-distribution" that contains the Dockerfile for the specific release of apmplanner2 and the linux distribution.
In anycase, I think that the best would be to use dockerhub to distribute pre-built images of apmplanner2.
=> Build: Refactor docker directory, create/update Dockerfiles

apm_planner.pro, src/output/kmlcreator.cc, src/output/kmlcreator.h, src/ui/AP2DataPlot2D.cpp, src/ui/AP2DataPlotAxisDialog.cc, src/ui/AP2DataPlotAxisDialog.h, src/ui/LogAnalysis.ui, src/ui/Loghandling/LogAnalysis.cpp, src/ui/Loghandling/LogAnalysis.h, src/ui/Loghandling/PresetManager.cpp, src/ui/Loghandling/PresetManager.h, src/ui/map/QGCMapWidget.cc
Hi all,
this is the PR for the new Loganalysis preset feature. As discussed in #1026 this brings individual configurable graphing presets for speeding up log analysis and view sharing between different analysis windows for easier comparison of log data.
Moreover there is a bugfix for waypoint lines not moving when panning the map, and an enhancement / fix for the KML export which should now export the plane model with correct yaw, roll and pitch. Also the CDATA in the export was fixed.
=> Preset feature and bugfixes

apm_planner.pro, src/configuration.h
Resolves correct OpenSSL library on Arch Linux.
https://github.com/ArduPilot/apm_planner/issues/1042
=> Build: Compile on Arch Linux.

src/ui/Loghandling/LogAnalysis.cpp, src/ui/Loghandling/LogParserBase.cpp, src/ui/Loghandling/LogParserBase.h, src/ui/Loghandling/LogdataStorage.cpp, src/ui/Loghandling/TlogParser.cpp, src/ui/qcustomplot.cpp, src/ui/qcustomplot.h
QCustom plot was released in version 2.0.0 so I updated to that version.
Besides that the tlog parser should be able to handle multiple flights in one log now. All time jumps bigger than 60sec are treated as a new flight and the last time stamp of the preceding log is used as time offset. All jumps smaller will be treated as an error.
The last commit (GraphView: Unchecked index lead to crash on empty logs.) is a partial fix for #1073. It fixes the crash but there is still the problem that mavlogdump.py dumps valid data where APM-Planner does not see any.
=> Qcustom plot and bugfixing

libs/opmapcontrol/src/common.pri, libs/opmapcontrol/src/core/cache.cpp, libs/opmapcontrol/src/internals/core.cpp, libs/opmapcontrol/src/internals/core.h, libs/opmapcontrol/src/internals/pureprojection.h, libs/opmapcontrol/src/mapwidget/mapwidget.pro, libs/opmapcontrol/src/mapwidget/waypointitem.cpp
While using the opmapcontrol lib in another project I came across some issues like memory leaks and deprecated project files. The committed changes fix those.
=> Some small fixes in opmapcontrol

src/ui/Loghandling/BinLogParser.cpp, src/ui/Loghandling/BinLogParser.h, src/ui/Loghandling/LogAnalysis.cpp, src/ui/QGCParamWidget.cc
A new PR for handling the NaNs in flash (*.bin) logs. Besides that two minor fixes are introduced as well. One adds some output to the log file which were only shown in GUI, the other one fixes the one wrong log output which always marked a successful log loading as cancelled.
=> NaN handling and small fixes

apm_planner.pro, libs/opmapcontrol/opmapcontrol_external.pri, libs/opmapcontrol/src/mapwidget/gpsitem.cpp, libs/opmapcontrol/src/mapwidget/gpsitem.h, libs/opmapcontrol/src/mapwidget/graphicsitem.h, libs/opmapcontrol/src/mapwidget/graphicsusertypes.h, libs/opmapcontrol/src/mapwidget/homeitem.cpp, libs/opmapcontrol/src/mapwidget/homeitem.h, libs/opmapcontrol/src/mapwidget/mapgraphicitem.cpp, libs/opmapcontrol/src/mapwidget/mapgraphicitem.h, libs/opmapcontrol/src/mapwidget/mapwidget.pro, libs/opmapcontrol/src/mapwidget/opmapwidget.cpp, libs/opmapcontrol/src/mapwidget/trailitem.h, libs/opmapcontrol/src/mapwidget/uavitem.cpp, libs/opmapcontrol/src/mapwidget/uavitem.h, libs/opmapcontrol/src/mapwidget/waypointitem.cpp, libs/opmapcontrol/src/mapwidget/waypointitem.h, libs/opmapcontrol/src/mapwidget/waypointlineitem.h, src/comm/LinkManager.cc, src/ui/Loghandling/BinLogParser.cpp, src/ui/Loghandling/BinLogParser.h, src/ui/Loghandling/LogAnalysis.cpp, src/ui/QGCParamWidget.cc, src/ui/map/MAV2DIcon.cc, src/ui/map/Waypoint2DIcon.cc, src/ui/uas/UASActionsWidget.cpp
Follow-up pull request to PR #1083 .
The commit introduces a new GraphicsItem base class for 1st-level child graphics items shown on the map (currently: GPSItem, HomeItem, UAVItem, WaypointItem). This approach allows an easy extension of the items and avoids duplicated code.
I struggled a bit with [mapgraphicitem.cpp:125](https://github.com/ArduPilot/apm_planner/pull/1085/files#diff-4ca69cb6bc9197e2f5d3734df23ca9acL125): Does it make sense to emit the mapChanged() signal after each item having updated its position or would it be sufficient to emit this signal once after all positions are updated?
=> Flightplan: Introduced GraphicsItem base class for graphics items on map

QGCExternalLibs.pri, README.md, apm_planner.pro, src/comm/MAVLinkProtocol.cc, src/configuration.h, src/ui/configuration/PX4FirmwareUploader.cc
Update in readme on how to build apm_planner in OpenBSD 6.2
Solves issue #1095
Changed EVP_PKEY_get0 to get1 to make it usable with both libressl and openssl.
m_enable_version_check uninitialized evaluates true in OpenBSD.
=> OpenBSD compatibility

src/ui/configuration/ApmFirmwareConfig.cc
@peterbarker confirmed that this change is permanent. There may be a
redirect in the future, but it does not work yet.
=> Firmware: changed URL, .eu is discontinued

src/ui/Loghandling/AsciiLogParser.cpp, src/ui/Loghandling/BinLogParser.cpp, src/ui/Loghandling/BinLogParser.h, src/ui/Loghandling/LogAnalysis.cpp, src/ui/Loghandling/LogExporter.cpp, src/ui/Loghandling/LogParserBase.cpp, src/ui/Loghandling/LogParserBase.h, src/ui/Loghandling/LogdataStorage.cpp, src/ui/Loghandling/LogdataStorage.h, src/ui/Loghandling/TlogParser.cpp, src/ui/Loghandling/TlogParser.h
This PR adds unit support to flashlog parser and to the datastorage. Flashlogs provided by the upcoming arducopter 3.6 provide unit information so all data can be scaled properly.
It solves #1089
=> Adding Unit support flashlog parser

src/uas/UAS.cc
Time sync message will now be answered correctly.
ekf_status and vibration message will not be flagged as not decodable any more (cause they are decoded).
=> Comms: Added support for timesync message

src/ui/Loghandling/LogdataStorage.cpp
When opened a dataflash log without unit data the application crashed when trying to plot the time filed.
=> GraphView: Bugfix for flashlog crashing when no unit data available.

src/uas/UAS.cc, src/uas/UASWaypointManager.cc, src/uas/UASWaypointManager.h
Hello APM Planner developers,
I found a problem that the waypoints drawn on the map are not accurate. According to this post: https://discuss.ardupilot.org/t/inaccurate-waypoint-logging-with-toggle-switch/26636, I believed that the error come from the conversion from float to double value. APM Planner requests and write waypoints gps position  in float, however, the Ardupilot system uses int32 to store the gps position for waypoints in default. So I changed the source code to make APM Planner request and write each waypoints in int32. The message ID for the mission item, which contains waypoint ID, should be MAVLINK_MSG_ID_MISSION_ITEM_INT rather than the MAVLINK_MSG_ID_MISSION_ITEM, and the mission item type should be mavlink_mission_item_int_t instead of mavlink_mission_item_t.
=> read and request int32 waypoints

src/uas/UAS.cc, src/uas/UAS.h, src/uas/UASManager.cc, src/ui/map/QGCMapWidget.cc
When receiving MAVLINK_MSG_ID_HOME_POSITION the UAV home position on map will be updated. The MAVLINK_MSG_ID_GPS_GLOBAL_ORIGIN reception will only store the position but will not bet treated as home pos anymore.
=> Enable set home

src/uas/UAS.cc, src/uas/UASWaypointManager.cc, src/uas/UASWaypointManager.h
#1179 added support for integer waypoints. However, the code does not distinguish between a MAVLink MISSION_REQUEST and MISSION_REQUEST_INT.
I added this feature here. @Arne-W and @niuxw What do you think?
=> mavlink: support both MISSION_REQUEST and MISSION_REQUEST_INT

src/ui/configuration/Radio3DRSettings.cc
Fixed telemetry radio configuration so it works with SiK 2.0 and it's derivatives.
Since 2.0, noone could configure or see radio settings in GUI.
This solution is tested with 1.9 (same format as previous) , 2.0, and 2.0variants.
Please make a new release.
=> Radio-Settings: added support for newer SiK versions

src/ui/configuration/Radio3DRSettings.cc
This doesn't work trivially on either of Xenial64 or Bionic64 installs
=> ui: Radio3DRSettings: don't use qAsConst

src/uas/UASWaypointManager.cc
This pull request fixes the following bug:
While uploading the waypoints to the UAS, a `mission_count` message is sent. The struct `mavlink_mission_count_t` has a field `mission_type`, which was not set and therefore had a random value (so in most cases 0). You can find the possible values in [MAVLink's common.h](https://github.com/ArduPilot/apm_planner/blob/master/libs/mavlink/include/mavlink/v2.0/common/common.h#L664-L666). I set it to `MAV_MISSION_TYPE_MISSION`.
Best,
Dino
=> Added mission type to MAVLink mission_count message

src/ui/mission/QGCMissionOther.cc
The new MAVLink version uses an [uint16 to store commands](https://github.com/ArduPilot/apm_planner/blob/master/libs/mavlink/include/mavlink/v2.0/common/mavlink_msg_mission_item.h#L16) (`MAV_CMD`). However, in the current master the value for commands is [limited to 255](https://github.com/ArduPilot/apm_planner/blob/master/src/ui/mission/QGCMissionOther.ui#L53). This pull request sets it to [the maximum allowable value](https://github.com/ArduPilot/apm_planner/blob/master/libs/mavlink/include/mavlink/v2.0/ardupilotmega/ardupilotmega.h#L215).
=> Allow MAV_CMD with values > 255

src/QGC.h, src/comm/MAVLinkProtocol.cc, src/comm/MAVLinkProtocol.h, src/comm/TLogReplayLink.cc, src/configuration.h, src/globalobject.cc, src/globalobject.h, src/uas/UAS.cc, src/ui/Loghandling/TlogParser.cpp, src/ui/Loghandling/TlogParser.h, src/ui/QGCSettingsWidget.cc, src/ui/QGCSettingsWidget.h, src/ui/QGCSettingsWidget.ui
Mavlink ID of APM Planner is configurable now.
=> General: Allow changing the Mavlink ID of APM Planner in advanced config dialog. Fixes #1228

src/ui/configuration/PX4FirmwareUploader.cc
During firmware updates, one is typically requested to replug the device.
On my system, the newly inserted device is nearly immediately detected by the planner, but the permissions on that device are not immediately set the right way (probably because `mtp-probe` needs to check it first). For this reason, firmware flashing is basically impossible.
This pull request introduces waiting for the device to become available with one-second sleeps between the attempts. While this is a dirty-ish hack, and something should have maybe done project-wide instead, I am not confident enough to do that. The introduced change just works for my use case, and is extremely unlikely to break anything.
This may probably fix #731, if I have guessed right which subsystem is responsible for that issue.
=> Firmware Install : Work around non-instant modem availability for PX4

src/uas/ArduPilotMegaMAV.cc
=> GraphView: Fix uint32 overflow when calculating time of Message arrows. Fixes #1246

src/configuration.h, src/globalobject.cc, src/globalobject.h, src/uas/UAS.cc, src/uas/UASWaypointManager.cc, src/uas/UASWaypointManager.h, src/ui/QGCSettingsWidget.cc, src/ui/QGCSettingsWidget.h, src/ui/QGCSettingsWidget.ui
Fixed timesync message using wrong mavlink ID. 
Added possibility to change the component ID used by APM-Planner when handling waypoints
=> Fix timesync message and more

.gitignore, libs/lib/Frameworks/SDL2.framework/Versions/A/Resources/Info.plist
we need to do 
make distclean
qmake -spec macx-clang apm_planner.pro
make -j8
to make sure the framework will be added properly into the build of the app
=> Build: Correction of the “.gitignore” and uploading missing file for SDL2 Fixes #1292

QGCSetup.pri, apm_planner.pro, src/main.cc
- there is nothing specific to MSVC2013 in the code, the project compiles/works with MSVC2019 just fine;
- MSVC-version specific deployement of runtime for version 2015 and higher is not implemented - to be done separately if needed;
---
This is not to claim the support of newer MSVC, but rather to allow local development/changes/experimantation.
=> Fix compilation with newer MSVC

QGCExternalLibs.pri
Fixes build issue in QtCreator from SDK include in macOS
Tested  macOS 14.3.1 with Qt5.15.12
=> Build: Fix #1309 SDL2 fails in QtCreator

libs/opmapcontrol/src/core/urlfactory.cpp
- Updates maps urls to use https which fixes issue on linux/windows
- NOTE: Does not fix non-functioning map tile providers.
=> Fixes #1197: Update map tile download to https

Vagrantfile
- Vagrant now uses Qt5 on ubuntu 22.04 LTS
- Drops using aqt as it does not have datavisualizations built in.
=> Fixes Vagrant file to use datavisualizations module
